language: python
python:
      - "2.7"
services:
      - rabbitmq
      - postgresql
addons:
      postgresql: "9.6"

install:
      - pip install -e .[testing,postgres]
script: 
      - py.test -xvls farine/tests/

